# Medical Cost Personal Datasets

In [ ]:
import pandas as pd
import numpy as np

In [33]:
print(np.__version__)
print(pd.__version__)

2.5.4
3.0.6

In [6]:
a = np.array([3,7,1,9])
print(a)
print(type(a))

[3 7 1 9]
<class 'numpy.ndarray'>

In [11]:
print("zeros: ", np.zeros(5))
print("ones: ", np.ones(6))
print("range: ", np.arange(0, 10, 2))
print("linspace: ", np.linspace(0, 1, 5))
print("identity:\n", np.eye(5))

zeros:  [0. 0. 0. 0. 0.]
ones:  [1. 1. 1. 1. 1. 1.]
range:  [0 2 4 6 8]
linspace:  [0.   0.25 0.5  0.75 1.  ]
identity:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

In [19]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
print("array:\n", x)
print("shape:", x.shape)
print("ndim: ", x.ndim)
print("size: ", x.size)
print("dtype: ", x.dtype)

array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
ndim:  2
size:  6
dtype:  int64

In [26]:
f = np.array([1, 2, 4], dtype = np.float64)
small = np.array([1, 2, 3], dtype = np.int8)

print(f, f.dtype)
print(small, small.dtype)
print("bytes per element:", f.itemsize, "vs", small.itemsize)

[1. 2. 4.] float64
[1 2 3] int8
bytes per element: 8 vs 1

In [27]:
prices = np.array([10.7, 3.2, 8.9])
print(prices.astype(int))

[10  3  8]

In [51]:
v = np.array([10, 20, 30, 40, 50])

print("first: ", v[0])
print("last: ", v[-1])
print("slice 1:3: ", v[1:3])
print("every other:", v[::2])
print("reversed: ", v[::-1])

first:  10
last:  50
slice 1:3:  [20 30]
every other: [10 30 50]
reversed:  [50 40 30 20 10]

In [53]:
print("v: ", v)
view = v[1:3]
view[0] = 999

print("view: ", view)
print("after editing the view:", v)

v = np.array([10, 20, 30, 40, 50])
independent = v[1:3].copy()
independent[0] = 999
print("after editing the copy:", v)

v:  [ 10 999  30  40  50]
view:  [999  30]
after editing the view: [ 10 999  30  40  50]
after editing the copy: [10 20 30 40 50]

In [63]:
m = np.arange(12).reshape(3, 4)
print(m)
print()
print("element at row 1, col 2:", m[1,2])
print("whole row 0: ", m[0, :])
print("column 3: ", m[:, 3])
print("top-left 2x2 block:\n", m[:2, :2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

element at row 1, col 2: 6
whole row 0:  [0 1 2 3]
column 3:  [ 3  7 11]
top-left 2x2 block:
 [[0 1]
 [4 5]]

In [67]:
claims = np.array([120, 45, 890, 230, 15, 640])
mask = claims > 200
print(mask)
print(claims[mask])
print(np.sum(mask))

[False False  True  True False  True]
[890 230 640]
3

In [ ]:
print(claims[(claims > 50) & (claims < 500)])
print(claims[(claims < 50) | (claims > 600)])
print(claims[~(claims > 200)])

[120 230]
[ 45 890  15 640]
[120  45  15]

In [71]:
flagged = np.where(claims > 200, "high", "low")
print(flagged)

['low' 'low' 'high' 'high' 'low' 'high']

In [83]:
costs = np.array([100.0, 250.0, 80.0])
print(costs)
print(costs + 10)
print(costs * 2)
print(costs * 1.05)
print(costs ** 2)
print(np.log(costs))

[100. 250.  80.]
[110. 260.  90.]
[200. 500. 160.]
[105.  262.5  84. ]
[10000. 62500.  6400.]
[4.60517019 5.52146092 4.38202663]

In [86]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a * b)

[10 40 90]

In [30]:
import pandas as pd

scores = pd.Series([90, 85], index = ["alice", "bob"])
score_frame = pd.DataFrame({"score": [90, 85]}, index=["alice", "bob"])


print(scores, type(scores))
print(score_frame, type(score_frame))

alice    90
bob      85
dtype: int64 <class 'pandas.Series'>
       score
alice     90
bob       85 <class 'pandas.DataFrame'>

In [7]:
import numpy as np
data = np.array([[4, 8, 6],
                 [1, 5, 9]])


print(data.sum())
print(data.mean())
print(data.sum(axis = 0))
print(data.sum(axis = 1))
print(data.max(axis=1))

33
5.5
[ 5 13 15]
[18 15]
[8 9]

In [14]:
monthly = np.array([[120, 90, 300],
                    [40, 45, 50],
                    [800, 60, 75]])
print(monthly)

print("total per patient: ", monthly.sum(axis=1))
print("average per month: ", monthly.mean(axis=0).round(2))
print("highest month per patient:", monthly.max(axis=1))

[[120  90 300]
 [ 40  45  50]
 [800  60  75]]
total per patient:  [510 135 935]
average per month:  [320.    65.   141.67]
highest month per patient: [300  50 800]

In [22]:
print("median:", np.median(monthly))
print("90th percentile:", np.percentile(monthly, 90).round(2))
print("index of largest value (flattened):", np.argmax(monthly))
print("running total: ", np.cumsum([1,2,3,4]))

median: 75.0
90th percentile: 400.0
index of largest value (flattened): 6
running total:  [ 1  3  6 10]

In [29]:
r = np.arange(12)
print("original:", r.shape)

print(r.reshape(3,4))
print(r.reshape(2,2,3).shape)
print(r.reshape(3, -1).shape)

original: (12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(2, 2, 3)
(3, 4)

In [33]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack([a, b]))
print(np.hstack([a,b]))
print(np.column_stack([a,b]))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]

In [37]:
t = np.array([[1, 2, 3],[4, 5, 6]])

print(t.T)
print(t.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)

In [48]:
rng = np.random.default_rng(seed = 42)

samples = rng.normal(loc=100, scale=15, size=5)
print(samples.round(2))

print("integers 0-9: ", rng.integers(0, 10, size=8))
print("shuffled: ",rng.permutation(np.arange(6)))

[104.57  84.4  111.26 114.11  70.73]
integers 0-9:  [5 9 7 7 7 7 5 1]
shuffled:  [4 0 2 3 5 1]

In [61]:
import time

n = 1_000_000
python_list = list(range(n))
print(len(python_list))
numpy_array = np.arange(n)
print(len(numpy_array))

start = time.perf_counter()
total = 0
for value in python_list:
    total += value * 2
loop_time = time.perf_counter() - start


start = time.perf_counter()
total_np = (numpy_array * 2).sum()
numpy_time = time.perf_counter() - start


start = time.perf_counter()
numpy_array2 = np.array(python_list)
total_np2 = (numpy_array2 * 2).sum()
numpy_time2 = time.perf_counter() - start


print(f"Python loop: {loop_time:.4f} s")
print(f"NumPy: {numpy_time:.4f} s")
print(f"Test run: {numpy_time2:.4f} s")
print(f"Both totals match: {total == total_np}")

1000000
1000000
Python loop: 0.3553 s
NumPy: 0.0026 s
Test run: 0.2543 s
Both totals match: True

In [62]:
import pandas as pd
import numpy as np

print(pd.__version__)

s = pd.Series([120, 45, 890], name = "claim_cost")
print(s)

3.0.6
0    120
1     45
2    890
Name: claim_cost, dtype: int64

In [64]:
df = pd.DataFrame({
    "name": ["Ana", "Ben", "Chloe"],
    "age": [34, 58, 41],
    "claim_cost": [120.0, 890.0, 45.0],
})
df

    name  age  claim_cost
0    Ana   34       120.0
1    Ben   58       890.0
2  Chloe   41        45.0

In [66]:
from io import StringIO

csv_text = """claim_id,patient_id,date,provider,type,amount,paid
1,P001,2025-01-04,Clinic A,outpatient,120.50,True
2,P002,2025-01-09,Hospital B,inpatient,8450.00,True
3,P001,2025-02-11,Clinic A,outpatient,45.00,False
4,P003,2025-02-20,Clinic C,pharmacy,15.25,True
5,P002,2025-03-02,Hospital B,outpatient,310.00,
6,P004,2025-03-15,Clinic A,outpatient,,True
7,P003,2025-03-28,Hospital B,inpatient,2200.75,True
8,P005,2025-04-01,Clinic C,pharmacy,980.00,True
"""

claims = pd.read_csv(StringIO(csv_text))
claims

   claim_id patient_id        date    provider        type   amount   paid
0         1       P001  2025-01-04    Clinic A  outpatient   120.50   True
1         2       P002  2025-01-09  Hospital B   inpatient  8450.00   True
2         3       P001  2025-02-11    Clinic A  outpatient    45.00  False
3         4       P003  2025-02-20    Clinic C    pharmacy    15.25   True
4         5       P002  2025-03-02  Hospital B  outpatient   310.00    NaN
5         6       P004  2025-03-15    Clinic A  outpatient      NaN   True
6         7       P003  2025-03-28  Hospital B   inpatient  2200.75   True
7         8       P005  2025-04-01    Clinic C    pharmacy   980.00   True

In [67]:
claims

   claim_id patient_id        date    provider        type   amount   paid
0         1       P001  2025-01-04    Clinic A  outpatient   120.50   True
1         2       P002  2025-01-09  Hospital B   inpatient  8450.00   True
2         3       P001  2025-02-11    Clinic A  outpatient    45.00  False
3         4       P003  2025-02-20    Clinic C    pharmacy    15.25   True
4         5       P002  2025-03-02  Hospital B  outpatient   310.00    NaN
5         6       P004  2025-03-15    Clinic A  outpatient      NaN   True
6         7       P003  2025-03-28  Hospital B   inpatient  2200.75   True
7         8       P005  2025-04-01    Clinic C    pharmacy   980.00   True

In [74]:
print("shape:", claims.shape)
print()
print(claims.dtypes)
print()
print(claims.head(3))
print()
print(claims.describe())

shape: (8, 7)

claim_id        int64
patient_id        str
date              str
provider          str
type              str
amount        float64
paid           object
dtype: object

   claim_id patient_id        date    provider        type  amount   paid
0         1       P001  2025-01-04    Clinic A  outpatient   120.5   True
1         2       P002  2025-01-09  Hospital B   inpatient  8450.0   True
2         3       P001  2025-02-11    Clinic A  outpatient    45.0  False

       claim_id       amount
count   8.00000     7.000000
mean    4.50000  1731.642857
std     2.44949  3064.010702
min     1.00000    15.250000
25%     2.75000    82.750000
50%     4.50000   310.000000
75%     6.25000  1590.375000
max     8.00000  8450.000000

In [75]:
claims.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   claim_id    8 non-null      int64
 1   patient_id  8 non-null      str
 2   date        8 non-null      str
 3   provider    8 non-null      str
 4   type        8 non-null      str
 5   amount      7 non-null      float64
 6   paid        7 non-null      object
dtypes: float64(1), int64(1), object(1), str(4)
memory usage: 580.0+ bytes

In [79]:
claims["date"]

0    2025-01-04
1    2025-01-09
2    2025-02-11
3    2025-02-20
4    2025-03-02
5    2025-03-15
6    2025-03-28
7    2025-04-01
Name: date, dtype: str

In [80]:
claims[["patient_id", "amount"]]

  patient_id   amount
0       P001   120.50
1       P002  8450.00
2       P001    45.00
3       P003    15.25
4       P002   310.00
5       P004      NaN
6       P003  2200.75
7       P005   980.00

In [84]:
print(claims.iloc[0])
print()
print(claims.loc[2, ["provider", "amount"]])
print()
print(claims.iloc[1:4, 2:5])

claim_id               1
patient_id          P001
date          2025-01-04
provider        Clinic A
type          outpatient
amount             120.5
paid                True
Name: 0, dtype: object

provider    Clinic A
amount          45.0
Name: 2, dtype: object

         date    provider        type
1  2025-01-09  Hospital B   inpatient
2  2025-02-11    Clinic A  outpatient
3  2025-02-20    Clinic C    pharmacy

In [91]:
claims.iloc[:, [1,2, 5, 6]]

  patient_id        date   amount   paid
0       P001  2025-01-04   120.50   True
1       P002  2025-01-09  8450.00   True
2       P001  2025-02-11    45.00  False
3       P003  2025-02-20    15.25   True
4       P002  2025-03-02   310.00    NaN
5       P004  2025-03-15      NaN   True
6       P003  2025-03-28  2200.75   True
7       P005  2025-04-01   980.00   True

In [89]:
claims

   claim_id patient_id        date    provider        type   amount   paid
0         1       P001  2025-01-04    Clinic A  outpatient   120.50   True
1         2       P002  2025-01-09  Hospital B   inpatient  8450.00   True
2         3       P001  2025-02-11    Clinic A  outpatient    45.00  False
3         4       P003  2025-02-20    Clinic C    pharmacy    15.25   True
4         5       P002  2025-03-02  Hospital B  outpatient   310.00    NaN
5         6       P004  2025-03-15    Clinic A  outpatient      NaN   True
6         7       P003  2025-03-28  Hospital B   inpatient  2200.75   True
7         8       P005  2025-04-01    Clinic C    pharmacy   980.00   True

In [93]:
large = claims[claims["amount"] > 500]
large

   claim_id patient_id        date    provider       type   amount  paid
1         2       P002  2025-01-09  Hospital B  inpatient  8450.00  True
6         7       P003  2025-03-28  Hospital B  inpatient  2200.75  True
7         8       P005  2025-04-01    Clinic C   pharmacy   980.00  True

In [94]:
clinic_outpatient = claims[
    (claims["provider"] == "Clinic A") & (claims["type"] == "outpatient")
]
clinic_outpatient

   claim_id patient_id        date  provider        type  amount   paid
0         1       P001  2025-01-04  Clinic A  outpatient   120.5   True
2         3       P001  2025-02-11  Clinic A  outpatient    45.0  False
5         6       P004  2025-03-15  Clinic A  outpatient     NaN   True

In [96]:
print(claims[claims["type"].isin(["inpatient", "pharmacy"])])
print()
print(claims[claims["provider"].str.contains("Hospital")])

   claim_id patient_id        date    provider       type   amount  paid
1         2       P002  2025-01-09  Hospital B  inpatient  8450.00  True
3         4       P003  2025-02-20    Clinic C   pharmacy    15.25  True
6         7       P003  2025-03-28  Hospital B  inpatient  2200.75  True
7         8       P005  2025-04-01    Clinic C   pharmacy   980.00  True

   claim_id patient_id        date    provider        type   amount  paid
1         2       P002  2025-01-09  Hospital B   inpatient  8450.00  True
4         5       P002  2025-03-02  Hospital B  outpatient   310.00   NaN
6         7       P003  2025-03-28  Hospital B   inpatient  2200.75  True

In [98]:
claims["amount_with_tax"] = claims["amount"] * 1.07
claims[["amount", "amount_with_tax"]]

    amount  amount_with_tax
0   120.50         128.9350
1  8450.00        9041.5000
2    45.00          48.1500
3    15.25          16.3175
4   310.00         331.7000
5      NaN              NaN
6  2200.75        2354.8025
7   980.00        1048.6000

In [103]:
claims["size"] = np.where(claims["amount"] > 500, "large", "small")
claims.loc[claims["paid"] == False, "size"] = "unpaid"
claims[["amount", "paid", "size"]]

    amount   paid    size
0   120.50   True   small
1  8450.00   True   large
2    45.00  False  unpaid
3    15.25   True   small
4   310.00    NaN   small
5      NaN   True   small
6  2200.75   True   large
7   980.00   True   large

In [104]:
claims

,claim_id,patient_id,date,provider,type,amount,paid,amount_with_tax,size
0,1,P001,2025-01-04,Clinic A,outpatient,120.50,True,128.9350,small
1,2,P002,2025-01-09,Hospital B,inpatient,8450.00,True,9041.5000,large
2,3,P001,2025-02-11,Clinic A,outpatient,45.00,False,48.1500,unpaid
3,4,P003,2025-02-20,Clinic C,pharmacy,15.25,True,16.3175,small
4,5,P002,2025-03-02,Hospital B,outpatient,310.00,NaN,331.7000,small
5,6,P004,2025-03-15,Clinic A,outpatient,NaN,True,NaN,small
6,7,P003,2025-03-28,Hospital B,inpatient,2200.75,True,2354.8025,large
7,8,P005,2025-04-01,Clinic C,pharmacy,980.00,True,1048.6000,large

In [105]:
claims = claims.drop(columns=["amount_with_tax"])
claims

,claim_id,patient_id,date,provider,type,amount,paid,size
0,1,P001,2025-01-04,Clinic A,outpatient,120.50,True,small
1,2,P002,2025-01-09,Hospital B,inpatient,8450.00,True,large
2,3,P001,2025-02-11,Clinic A,outpatient,45.00,False,unpaid
3,4,P003,2025-02-20,Clinic C,pharmacy,15.25,True,small
4,5,P002,2025-03-02,Hospital B,outpatient,310.00,NaN,small
5,6,P004,2025-03-15,Clinic A,outpatient,NaN,True,small
6,7,P003,2025-03-28,Hospital B,inpatient,2200.75,True,large
7,8,P005,2025-04-01,Clinic C,pharmacy,980.00,True,large

In [107]:
claims.columns.tolist()

['claim_id',
 'patient_id',
 'date',
 'provider',
 'type',
 'amount',
 'paid',
 'size']

In [2]:
import pandas as pd
import numpy as np

print(pd.__version__)

s = pd.Series([120, 45, 890], name = "claim_cost")
print(s)

3.0.6
0    120
1     45
2    890
Name: claim_cost, dtype: int64

In [5]:
df = pd.DataFrame({
    "name": ["Ana", "Ben", "Chloe"],
    "age": [34, 58, 41],
    "claim_cost": [120.0, 890.0, 45.0],
})
df

    name  age  claim_cost
0    Ana   34       120.0
1    Ben   58       890.0
2  Chloe   41        45.0

In [29]:
from io import StringIO

csv_text = """claim_id,patient_id,date,provider,type,amount,paid
1,P001,2025-01-04,Clinic A,outpatient,120.50,True
2,P002,2025-01-09,Hospital B,inpatient,8450.00,True
3,P001,2025-02-11,Clinic A,outpatient,45.00,False
4,P003,2025-02-20,Clinic C,pharmacy,15.25,True
5,P002,2025-03-02,Hospital B,outpatient,310.00,
6,P004,2025-03-15,Clinic A,outpatient,,True
7,P003,2025-03-28,Hospital B,inpatient,2200.75,True
8,P005,2025-04-01,Clinic C,pharmacy,980.00,True
"""

claims = pd.read_csv(StringIO(csv_text))
claims

   claim_id patient_id        date    provider        type   amount   paid
0         1       P001  2025-01-04    Clinic A  outpatient   120.50   True
1         2       P002  2025-01-09  Hospital B   inpatient  8450.00   True
2         3       P001  2025-02-11    Clinic A  outpatient    45.00  False
3         4       P003  2025-02-20    Clinic C    pharmacy    15.25   True
4         5       P002  2025-03-02  Hospital B  outpatient   310.00    NaN
5         6       P004  2025-03-15    Clinic A  outpatient      NaN   True
6         7       P003  2025-03-28  Hospital B   inpatient  2200.75   True
7         8       P005  2025-04-01    Clinic C    pharmacy   980.00   True

In [ ]:
print(claims.shape)
print(claims.dtypes)
print(claims.head(3))
print(claims.describe())

(8, 7)
claim_id        int64
patient_id        str
date              str
provider          str
type              str
amount        float64
paid           object
dtype: object
   claim_id patient_id        date    provider        type  amount   paid
0         1       P001  2025-01-04    Clinic A  outpatient   120.5   True
1         2       P002  2025-01-09  Hospital B   inpatient  8450.0   True
2         3       P001  2025-02-11    Clinic A  outpatient    45.0  False
       claim_id       amount
count   8.00000     7.000000
mean    4.50000  1731.642857
std     2.44949  3064.010702
min     1.00000    15.250000
25%     2.75000    82.750000
50%     4.50000   310.000000
75%     6.25000  1590.375000
max     8.00000  8450.000000

In [12]:
claims.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   claim_id    8 non-null      int64
 1   patient_id  8 non-null      str
 2   date        8 non-null      str
 3   provider    8 non-null      str
 4   type        8 non-null      str
 5   amount      7 non-null      float64
 6   paid        7 non-null      object
dtypes: float64(1), int64(1), object(1), str(4)
memory usage: 580.0+ bytes

In [30]:
claims["amount"]

0     120.50
1    8450.00
2      45.00
3      15.25
4     310.00
5        NaN
6    2200.75
7     980.00
Name: amount, dtype: float64

In [15]:
claims[["patient_id", "amount"]]

  patient_id   amount
0       P001   120.50
1       P002  8450.00
2       P001    45.00
3       P003    15.25
4       P002   310.00
5       P004      NaN
6       P003  2200.75
7       P005   980.00

In [31]:
print(claims.iloc[2])

print(claims.loc[2, ["provider", "amount"]])

print(claims.iloc[1:4, 2:5])

claim_id               3
patient_id          P001
date          2025-02-11
provider        Clinic A
type          outpatient
amount              45.0
paid               False
Name: 2, dtype: object
provider    Clinic A
amount          45.0
Name: 2, dtype: object
         date    provider        type
1  2025-01-09  Hospital B   inpatient
2  2025-02-11    Clinic A  outpatient
3  2025-02-20    Clinic C    pharmacy

In [32]:
claims["amount_with_tax"] = claims["amount"]* 1.07
claims[["amount", "amount_with_tax"]]

    amount  amount_with_tax
0   120.50         128.9350
1  8450.00        9041.5000
2    45.00          48.1500
3    15.25          16.3175
4   310.00         331.7000
5      NaN              NaN
6  2200.75        2354.8025
7   980.00        1048.6000

In [33]:
claims["size"] = np.where(claims["amount"] > 500, "large", "small")
claims.loc[claims["paid"] == False, "size"] = "unpaid"
claims[["amount", "paid", "size"]]

    amount   paid    size
0   120.50   True   small
1  8450.00   True   large
2    45.00  False  unpaid
3    15.25   True   small
4   310.00    NaN   small
5      NaN   True   small
6  2200.75   True   large
7   980.00   True   large

In [34]:
claims = claims.drop(columns=["amount_with_tax"])
claims.columns.tolist()

['claim_id',
 'patient_id',
 'date',
 'provider',
 'type',
 'amount',
 'paid',
 'size']

In [37]:
print(claims.isna())
print(claims.isna().sum())

   claim_id  patient_id   date  provider   type  amount   paid   size
0     False       False  False     False  False   False  False  False
1     False       False  False     False  False   False  False  False
2     False       False  False     False  False   False  False  False
3     False       False  False     False  False   False  False  False
4     False       False  False     False  False   False   True  False
5     False       False  False     False  False    True  False  False
6     False       False  False     False  False   False  False  False
7     False       False  False     False  False   False  False  False
claim_id      0
patient_id    0
date          0
provider      0
type          0
amount        1
paid          1
size          0
dtype: int64

In [38]:
print("rows with any missing value:")
print(claims[claims.isna().any(axis=1)])

rows with any missing value:
   claim_id patient_id        date    provider        type  amount  paid  \
4         5       P002  2025-03-02  Hospital B  outpatient   310.0   NaN
5         6       P004  2025-03-15    Clinic A  outpatient     NaN  True

    size
4  small
5  small

In [43]:
claims.dropna(subset=["amount"])

,claim_id,patient_id,date,provider,type,amount,paid,size
0,1,P001,2025-01-04,Clinic A,outpatient,120.50,True,small
1,2,P002,2025-01-09,Hospital B,inpatient,8450.00,True,large
2,3,P001,2025-02-11,Clinic A,outpatient,45.00,False,unpaid
3,4,P003,2025-02-20,Clinic C,pharmacy,15.25,True,small
4,5,P002,2025-03-02,Hospital B,outpatient,310.00,NaN,small
6,7,P003,2025-03-28,Hospital B,inpatient,2200.75,True,large
7,8,P005,2025-04-01,Clinic C,pharmacy,980.00,True,large

In [45]:
claims.dropna(subset=["amount","paid"])

,claim_id,patient_id,date,provider,type,amount,paid,size
0,1,P001,2025-01-04,Clinic A,outpatient,120.50,True,small
1,2,P002,2025-01-09,Hospital B,inpatient,8450.00,True,large
2,3,P001,2025-02-11,Clinic A,outpatient,45.00,False,unpaid
3,4,P003,2025-02-20,Clinic C,pharmacy,15.25,True,small
6,7,P003,2025-03-28,Hospital B,inpatient,2200.75,True,large
7,8,P005,2025-04-01,Clinic C,pharmacy,980.00,True,large

In [48]:
amount_filled = claims["amount"].fillna(claims["amount"].median())
print(claims["amount"].median())
print(amount_filled)

310.0
0     120.50
1    8450.00
2      45.00
3      15.25
4     310.00
5     310.00
6    2200.75
7     980.00
Name: amount, dtype: float64

In [51]:
print(claims.info())
claims

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   claim_id    8 non-null      int64
 1   patient_id  8 non-null      str
 2   date        8 non-null      str
 3   provider    8 non-null      str
 4   type        8 non-null      str
 5   amount      7 non-null      float64
 6   paid        7 non-null      object
 7   size        8 non-null      str
dtypes: float64(1), int64(1), object(1), str(5)
memory usage: 644.0+ bytes
None

,claim_id,patient_id,date,provider,type,amount,paid,size
0,1,P001,2025-01-04,Clinic A,outpatient,120.50,True,small
1,2,P002,2025-01-09,Hospital B,inpatient,8450.00,True,large
2,3,P001,2025-02-11,Clinic A,outpatient,45.00,False,unpaid
3,4,P003,2025-02-20,Clinic C,pharmacy,15.25,True,small
4,5,P002,2025-03-02,Hospital B,outpatient,310.00,NaN,small
5,6,P004,2025-03-15,Clinic A,outpatient,NaN,True,small
6,7,P003,2025-03-28,Hospital B,inpatient,2200.75,True,large
7,8,P005,2025-04-01,Clinic C,pharmacy,980.00,True,large

In [55]:
claims["paid"] = claims["paid"].fillna(False).astype(bool)
claims

,claim_id,patient_id,date,provider,type,amount,paid,size
0,1,P001,2025-01-04,Clinic A,outpatient,120.50,True,small
1,2,P002,2025-01-09,Hospital B,inpatient,8450.00,True,large
2,3,P001,2025-02-11,Clinic A,outpatient,45.00,False,unpaid
3,4,P003,2025-02-20,Clinic C,pharmacy,15.25,True,small
4,5,P002,2025-03-02,Hospital B,outpatient,310.00,False,small
5,6,P004,2025-03-15,Clinic A,outpatient,NaN,True,small
6,7,P003,2025-03-28,Hospital B,inpatient,2200.75,True,large
7,8,P005,2025-04-01,Clinic C,pharmacy,980.00,True,large

In [56]:
claims[["claim_id", "paid"]]

   claim_id   paid
0         1   True
1         2   True
2         3  False
3         4   True
4         5  False
5         6   True
6         7   True
7         8   True

In [58]:
claims.dtypes

claim_id        int64
patient_id        str
date              str
provider          str
type              str
amount        float64
paid             bool
size              str
dtype: object

In [60]:
claims.sort_values("amount", ascending=False).head(3)

,claim_id,patient_id,date,provider,type,amount,paid,size
1,2,P002,2025-01-09,Hospital B,inpatient,8450.00,True,large
6,7,P003,2025-03-28,Hospital B,inpatient,2200.75,True,large
7,8,P005,2025-04-01,Clinic C,pharmacy,980.00,True,large

In [61]:
claims.sort_values(["provider", "amount"])[["provider", "amount"]]

     provider   amount
2    Clinic A    45.00
0    Clinic A   120.50
5    Clinic A      NaN
3    Clinic C    15.25
7    Clinic C   980.00
4  Hospital B   310.00
6  Hospital B  2200.75
1  Hospital B  8450.00

In [66]:
claims["amount"]

0     120.50
1    8450.00
2      45.00
3      15.25
4     310.00
5        NaN
6    2200.75
7     980.00
Name: amount, dtype: float64

In [67]:
claims["amount"].rank(ascending=False)

0    5.0
1    1.0
2    6.0
3    7.0
4    4.0
5    NaN
6    2.0
7    3.0
Name: amount, dtype: float64

In [71]:
claims.groupby("provider")["amount"].sum()

provider
Clinic A        165.50
Clinic C        995.25
Hospital B    10960.75
Name: amount, dtype: float64

In [73]:
summary = claims.groupby("type").agg(
    total_claims =("claim_id", "count"),
    total_amount =("amount", "sum"),
    avg_amount=("amount", "mean"),
)
summary

            total_claims  total_amount  avg_amount
type
inpatient              2      10650.75    5325.375
outpatient             4        475.50     158.500
pharmacy               2        995.25     497.625

In [74]:
claims.groupby(["provider", "type"])["amount"].agg(["count", "sum"])

                       count       sum
provider   type
Clinic A   outpatient      2    165.50
Clinic C   pharmacy        2    995.25
Hospital B inpatient       2  10650.75
           outpatient      1    310.00

In [75]:
claims

,claim_id,patient_id,date,provider,type,amount,paid,size
0,1,P001,2025-01-04,Clinic A,outpatient,120.50,True,small
1,2,P002,2025-01-09,Hospital B,inpatient,8450.00,True,large
2,3,P001,2025-02-11,Clinic A,outpatient,45.00,False,unpaid
3,4,P003,2025-02-20,Clinic C,pharmacy,15.25,True,small
4,5,P002,2025-03-02,Hospital B,outpatient,310.00,False,small
5,6,P004,2025-03-15,Clinic A,outpatient,NaN,True,small
6,7,P003,2025-03-28,Hospital B,inpatient,2200.75,True,large
7,8,P005,2025-04-01,Clinic C,pharmacy,980.00,True,large

In [76]:
claims["provider"].value_counts()

provider
Clinic A      3
Hospital B    3
Clinic C      2
Name: count, dtype: int64

In [77]:
claims.dtypes

claim_id        int64
patient_id        str
date              str
provider          str
type              str
amount        float64
paid             bool
size              str
dtype: object

In [80]:
pd.pivot_table(
    claims,
    index="provider",
    columns="type",
    values="amount",
    aggfunc="sum",
    fill_value=0,
)

type        inpatient  outpatient  pharmacy
provider
Clinic A         0.00       165.5      0.00
Clinic C         0.00         0.0    995.25
Hospital B   10650.75       310.0      0.00

In [81]:
patients = pd.DataFrame({
    "patient_id": ["P001", "P002", "P003", "P004", "P005"],
    "plan": ["Gold", "Silver", "Gold", "Bronze", "Silver"],
    "age": [34, 58, 41, 27, 66],
})
patients

  patient_id    plan  age
0       P001    Gold   34
1       P002  Silver   58
2       P003    Gold   41
3       P004  Bronze   27
4       P005  Silver   66

In [84]:
joined = claims.merge(patients, on = "patient_id", how = "left")
joined[["claim_id", "patient_id", "plan", "age", "amount"]]

   claim_id patient_id    plan  age   amount
0         1       P001    Gold   34   120.50
1         2       P002  Silver   58  8450.00
2         3       P001    Gold   34    45.00
3         4       P003    Gold   41    15.25
4         5       P002  Silver   58   310.00
5         6       P004  Bronze   27      NaN
6         7       P003    Gold   41  2200.75
7         8       P005  Silver   66   980.00

In [82]:
claims

,claim_id,patient_id,date,provider,type,amount,paid,size
0,1,P001,2025-01-04,Clinic A,outpatient,120.50,True,small
1,2,P002,2025-01-09,Hospital B,inpatient,8450.00,True,large
2,3,P001,2025-02-11,Clinic A,outpatient,45.00,False,unpaid
3,4,P003,2025-02-20,Clinic C,pharmacy,15.25,True,small
4,5,P002,2025-03-02,Hospital B,outpatient,310.00,False,small
5,6,P004,2025-03-15,Clinic A,outpatient,NaN,True,small
6,7,P003,2025-03-28,Hospital B,inpatient,2200.75,True,large
7,8,P005,2025-04-01,Clinic C,pharmacy,980.00,True,large

In [85]:
joined

,claim_id,patient_id,date,provider,type,amount,paid,size,plan,age
0,1,P001,2025-01-04,Clinic A,outpatient,120.50,True,small,Gold,34
1,2,P002,2025-01-09,Hospital B,inpatient,8450.00,True,large,Silver,58
2,3,P001,2025-02-11,Clinic A,outpatient,45.00,False,unpaid,Gold,34
3,4,P003,2025-02-20,Clinic C,pharmacy,15.25,True,small,Gold,41
4,5,P002,2025-03-02,Hospital B,outpatient,310.00,False,small,Silver,58
5,6,P004,2025-03-15,Clinic A,outpatient,NaN,True,small,Bronze,27
6,7,P003,2025-03-28,Hospital B,inpatient,2200.75,True,large,Gold,41
7,8,P005,2025-04-01,Clinic C,pharmacy,980.00,True,large,Silver,66

In [86]:
jan = pd.DataFrame({"claim_id": [101], "amount": [50.0]})
feb = pd.DataFrame({"claim_id": [102], "amount": [75.0]})

In [87]:
jan

   claim_id  amount
0       101    50.0

In [93]:
claims.dtypes

claim_id        int64
patient_id        str
date              str
provider          str
type              str
amount        float64
paid             bool
size              str
dtype: object

In [91]:
pd.concat([jan, feb], ignore_index=True)

   claim_id  amount
0       101    50.0
1       102    75.0

In [94]:
claims["date"] = pd.to_datetime(claims["date"])

In [95]:
claims.dtypes

claim_id               int64
patient_id               str
date          datetime64[us]
provider                 str
type                     str
amount               float64
paid                    bool
size                     str
dtype: object

In [100]:
claims["month"] = claims["date"].dt.to_period("M")
claims["date"].dt.to_period("M")

0    2025-01
1    2025-01
2    2025-02
3    2025-02
4    2025-03
5    2025-03
6    2025-03
7    2025-04
Name: date, dtype: period[M]

In [102]:
claims["weekday"] = claims["date"].dt.day_name()

In [104]:
claims["date"].dt.day_name()

0    Saturday
1    Thursday
2     Tuesday
3    Thursday
4      Sunday
5    Saturday
6      Friday
7     Tuesday
Name: date, dtype: str

In [105]:
claims

,claim_id,patient_id,date,provider,type,amount,paid,size,month,weekday
0,1,P001,2025-01-04,Clinic A,outpatient,120.50,True,small,2025-01,Saturday
1,2,P002,2025-01-09,Hospital B,inpatient,8450.00,True,large,2025-01,Thursday
2,3,P001,2025-02-11,Clinic A,outpatient,45.00,False,unpaid,2025-02,Tuesday
3,4,P003,2025-02-20,Clinic C,pharmacy,15.25,True,small,2025-02,Thursday
4,5,P002,2025-03-02,Hospital B,outpatient,310.00,False,small,2025-03,Sunday
5,6,P004,2025-03-15,Clinic A,outpatient,NaN,True,small,2025-03,Saturday
6,7,P003,2025-03-28,Hospital B,inpatient,2200.75,True,large,2025-03,Friday
7,8,P005,2025-04-01,Clinic C,pharmacy,980.00,True,large,2025-04,Tuesday

In [107]:
claims[["date", "month", "weekday"]]

        date    month   weekday
0 2025-01-04  2025-01  Saturday
1 2025-01-09  2025-01  Thursday
2 2025-02-11  2025-02   Tuesday
3 2025-02-20  2025-02  Thursday
4 2025-03-02  2025-03    Sunday
5 2025-03-15  2025-03  Saturday
6 2025-03-28  2025-03    Friday
7 2025-04-01  2025-04   Tuesday

In [108]:
claims.groupby("month")["amount"].sum()

month
2025-01    8570.50
2025-02      60.25
2025-03    2510.75
2025-04     980.00
Freq: M, Name: amount, dtype: float64

In [113]:
result = (
    claims
    .dropna(subset=["amount"])
    .query("paid == True")
    .groupby("provider")["amount"]
    .agg(["count", "mean"])
    .round(2)
    .sort_values("mean", ascending=False)
)
result

            count     mean
provider
Hospital B      2  5325.38
Clinic C        2   497.62
Clinic A        1   120.50

In [116]:
list(claims.columns)

['claim_id',
 'patient_id',
 'date',
 'provider',
 'type',
 'amount',
 'paid',
 'size',
 'month',
 'weekday']